module.exports = {
  "3DGrid" : 1 ,
  "AdjustRGB" : 2,
  "AutoColorEnhance" : 3,
  "AutoColorLevel" : 4,
  "AutoContrast" : 5,
  "Bulge" : 6,
  //"Perspective" : 7,
  "Ribbon" : 8,
  "Ripple" : 9,
  "Rotate" : 10,
  "Shear" :11,
  "Twist" : 12 ,
  "Wave" : 13,
  "BlindsX" : 14,
  "BlindsY" :15 ,
  "BlurGauss":16,
  "BlurMotion" : 17,
  "BlurRadial" : 18,
  "BlurZoom" : 19,
  "BrightnessContrast" : 20,
  "ColorTone" : 22,
  "Gamma" : 23,
  "Mosaic" : 24,
  "Noisify" : 25,
  //"OilPaint" : 26,
  "OldPhoto" : 27,
  "PencilSketch":28
}
